apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{ toYaml .Values.labels | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{ toYaml .Values.labels | indent 6 }}
  template:
    metadata:
      labels:
        {{ toYaml .Values.labels | indent 8 }}
    spec:
      serviceAccountName: {{ .Values.name }}
      initContainers:
        - name: config-init-from-vault
          image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/config-init-from-vault:latest
          imagePullPolicy: Always
          env:
            - name: ENV
              value: {{ .Values.env }}
            - name: APP_NAME
              value: {{ .Values.name }}
          envFrom:
          - secretRef:
              name: vault
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          {{ if .Values.customCommand.enabled }}
          command: ["java"]
          args: {{ .Values.customCommand.command }}
          {{ end }}
          envFrom:
          - secretRef:
              name: {{ .Values.name }}
          ports:
          - containerPort: {{ .Values.containerPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}



