{{ if .Values.schema.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-schema-load
spec:
  template:
    spec:
      containers:
      - name: schema-load
        image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
      restartPolicy: Never
  backoffLimit: 1
{{ end }}

